version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - 5432:5432

volumes:
  postgres_volume:
